### ISSUE TITLE
hpss crashes

### ISSUE THREAD

**Issue by tremblap** [flucoma/flucoma-pd#55] opened 2022-06-08 16:14 UTC
loading the helpfile in PR47 crashes:

Assertion failed: (hSize <= mMaxBuf.cols()), function init, file /Users/pa/Documents/documents@hudd/research/projects/fluid corpus navigation/research/fluid_decomposition/include/clients/rt/../../algorithms/public/HPSS.hpp, line 47.

it seems to be relating to arguments.

> Assertion failed: (hSize <= mMaxBuf.cols()), function init, file /Users/pa/Documents/documents@hudd/research/projects/fluid corpus navigation/research/fluid_decomposition/include/clients/rt/../../algorithms/public/HPSS.hpp, line 47.

**Comment by weefuzzy** [comment] 2022-06-08 16:18
This is a duplicate of #51 ?

**Comment by tremblap** [comment] 2022-06-08 16:20
it seems so. sorry for the noise. I'll amend.

**Closed** 2022-06-08 16:20 UTC
